### ISSUE TITLE
getToken by name

### ISSUE THREAD

**Issue by xenoterracide** [mscharley/inversify-token#245]
since an interface/token is good when you have multiple implementations, is there any way I can qualify

```ts
getToken(container, MyInterface)
```
by name? like `@named(...)`

**Comment by mscharley** [comment]
Hi,

I haven't really needed to use `@named` before, do you have a more complete example of what you're looking for? I think the answer is probably "not yet" though.

**Comment by mscharley** [comment]
That will definitely do the trick, and since you're using TokenType it will be stable, even if you change the type that the token provides. Using `token.identifier` is an escape hatch that should be functional in all cases, but it's not quite as nice or type safe as what you could get if I provided an actual `getTokenNamed()` though.

**Comment by xenoterracide** [comment]
what you're really trying to achieve here is basically aurelia 2's `createInterface` (I added more functionality to it) https://github.com/aurelia/aurelia/blob/master/packages/kernel/src/di.ts#L212 unfortunately, of course, that API requires this to be integrated into inversify core.

might be good to add something like `getTokenBy(container, Axios).named('axios')` so it's extensible...

**Comment by xenoterracide** [comment]
and for the default behavior it could be done as `getTokenBy(container, Axios).()` maybe

**Comment by mscharley** [comment]
Just looking back into this finally, and as far as I can tell everything is there.

```
import { getNamed } from "inversify-token";

const tokenContainerModule = new TokenContainerModule(bind => {
  // Constant REST Clients
  bind(Axios)
    .toConstantValue(
      withTracingInterceptor(
        axios.create({
          baseURL: env.SSO_BASE_URL,
        }),
      ),
    )
    .whenTargetNamed(ssoClient)
});

container.load(tokenContainerModule);

const ssoAxios = getNamed(tokenContainerModule, Axios, ssoClient);

class Foo {
  constructor(@injectToken(Axios) @named(ssoClient) public ssoAxios: Axios) {}
}
```

If I'm missing something then let me know, but for now I'm going to close this ticket.
